GET http://localhost:3000/api/hello

###

POST http://localhost:3000/api/hello
content-type: application/json

{
  "title": "title 20",
  "description": "dewsc"
}

###

POST http://localhost:3000/api/auth?nextApi=/hello
content-type: application/json

{
  "title": "title 20",
  "description": "dewsc"
}