GET http://localhost:3000/api/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJyb2wiOiJIVU1BTiIsImlkIjoiNjMzMGY5Y2Y2NWU0NjM1ODY3OGI1YzZlIiwiaWF0IjoxNjY0MTU0MDY0fQ.IrbN3Jh4HE1ECzhZZrmS3csSnrSnVV4FZBLHvFy02Zs

###

POST http://localhost:3000/api/hello
content-type: application/json

{
  "title": "title 20",
  "description": "dewsc"
}

###

POST http://localhost:3000/api/auth?nextApi=/hello
content-type: application/json

{
  "title": "title 20",
  "description": "dewsc"
}