# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main', 'pre-release']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Verify pnpm installation
        run: pnpm --version
      - name: Install dependencies
        run: pnpm install
      - name: Build Next.js app
        run: pnpm build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Configurar el repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # Instalar pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # Desplegar la aplicación
      - name: Deploy
        run: |
          pnpm install
          pnpm build
          pnpm start
